#Variables
@baseurl = http://localhost:3333

# health check
# @name healthCheck
GET {{baseurl}}/health

###

# Get rooms
# @name getRooms
GET {{baseurl}}/rooms

###

# Create room
# @name createRoom
POST {{baseurl}}/rooms
Content-Type: application/json

{
  "name": "Sala de teste",
  "description": "Essa é uma sala de teste"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

#Get Room Question
# @name getRoomQuestion
GET {{baseurl}}/rooms/{{roomId}}/questions

###

#Create question
# @name createQuestion
POST {{baseurl}}/rooms/8efccc45-bd3e-43f2-b195-8bcdf3a9f9a5/questions
Content-Type: application/json

{
  "question": "Oque é Vue.js e a sua diferença em relação ao Angular"
}